// Generates seed.sql from data/projects.json, data/members.json, data/events.json.
// Run: node scripts/generate-seed.js  -> writes seed.sql
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
// Projects are intentionally seeded empty — admin creates them through the
// authenticated admin panel (with uploaded images). members/events still seed.
const tables = ['members', 'events'];

function sqlStr(s) {
  return "'" + String(s).replace(/'/g, "''") + "'";
}

let out = '-- Generated by scripts/generate-seed.js — do not edit by hand.\n';

// Projects start empty; admin populates them via the admin panel.
out += '\nDELETE FROM projects;\n';

for (const table of tables) {
  const records = JSON.parse(fs.readFileSync(path.join(root, 'data', table + '.json'), 'utf8'));
  out += '\nDELETE FROM ' + table + ';\n';
  records.forEach((rec, i) => {
    const id = rec.id || (table + '-' + i);
    out += 'INSERT INTO ' + table + ' (id, position, data) VALUES ('
      + sqlStr(id) + ', ' + i + ', ' + sqlStr(JSON.stringify(rec)) + ');\n';
  });
  console.log(table + ': ' + records.length + ' rows');
}

fs.writeFileSync(path.join(root, 'seed.sql'), out);
console.log('Wrote seed.sql');
